### ISSUE TITLE
Remove generic-asset pallet on dex parachain side

### ISSUE THREAD

**Issue by iorveth** [subdarkdex/subdex-parachain#3]
## Background
- `generic-asset` pallet provides broad functionality to work with tokens throughout the chain. 

- We only used it to track user balances and perform dex specific operations. 
- As a result, the features, provided by `generic-asset` left mostly unused. It also was removed from substrate 2.0 default frame modules.

## Proposal
1. Remove `generic-asset` pallet on DEX para-chain side, implementing needed functionality by ourselves.
1. Upgrade `dex_xcmp` pallet to work with our internal implementation.

As a result we`ll get much more flexible and suitable implementation, eliminating the necessity to depend on external pallet.

**Comment by whalelephant** [comment]
**Remove generic-asset pallet on DEX para-chain side, implementing needed functionality by ourselves.
👍** 

**Upgrade generic `token-dealer` pallet to work with our internal implementation.**
Please elaborate, we have 2 pallets that does `token dealer` communications no. 5 and no. 6 below. Do you mean for Dex-XCMP?

| Number | Deliverable                 | Specification                                                                                                                                                                                                                                                                 |
| ------ | --------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 4.     | Dex Pallet                  | Implement Uniswap V2 AMM protocol with full test coverage and eliminate overflow/underflow risks in calculation in the chain, publish as a standalone pallet                                                                                                                  |
| 5.     | Dex XCMP Pallet             | Handle relay chain asset creation and test this placeholder XCMP pallet that will be used to create demo for testnets for this milestone                                                                                                                                      |
| 6.     | Generic Token Dealer Pallet | Create a generic token dealer pallet that can handle generic assets and/or native parachain currency, based on the [token dealer](https://github.com/paritytech/cumulus/tree/master/rococo-parachains/pallets/token-dealer) pallet example and publish as a standalone pallet |

**Comment by iorveth** [comment]
@whalelephant , i mean dex_xcmp, thank you for pointing!

**Comment by iorveth** [comment]
Done in https://github.com/subdarkdex/subdex-parachains-1/pull/4
